version: "2"

services:
  zookeeper:
    image: docker.io/bitnami/zookeeper:3.8
    ports:
      - "2181:2181"
    volumes:
      - "zookeeper_data:/bitnami"
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
  kafka:
    image: docker.io/bitnami/kafka:3.2
    ports:
      - "29092:29092"
    volumes:
      - "kafka_data:/bitnami"
      - '/home/arturg/repos/binance-trader/kafka/topics.sh:/docker-entrypoint-initdb.d/topics.sh'
    environment:
      # - KAFKA_BROKER_ID=1
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_CFG_LISTENERS=INTERNAL://:9092,EXTERNAL://:29092
      - KAFKA_CFG_ADVERTISED_LISTENERS=INTERNAL://kafka:9092,EXTERNAL://localhost:29092
      - KAFKA_CFG_INTER_BROKER_LISTENER_NAME=INTERNAL
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
    depends_on:
      - zookeeper
  akhq:
    image: tchiotludo/akhq
    ports: 
      - '8080:8080'
    volumes:
      - '/home/arturg/repos/binance-trader/akhq/application.yml:/app/application.yml'
    depends_on:
      - kafka


volumes:
  zookeeper_data:
    driver: local
  kafka_data:
    driver: local
